### ISSUE TITLE
Testing: Redact Values module

### ISSUE THREAD

**Issue by jimsafley** [omeka-s-modules/RedactValues#1]
This module introduces the ability for administrators to redact property values. Install the module and click on "Redact Values" in the navigation. Here is where you will manage your redactions. Click on "Add redaction" and fill out the form. You will be able to choose a resource type, build a query to filter the resources, select the property from which to redact text, select the pattern to use for redaction, enter the replacement text, and choose what lower roles will be allowed to view redacted text. Be sure to read the information provided on the form to get a better idea of what to enter.

The best way to test the module is to add a few redactions using the patterns that come with the module (URL, email. IP address), and add a few items that have property values that contain a URL, email, and IP address. Then open your browser in incognito mode,  log in as an author or researcher, and view the items you just created. Any URL, email, and IP address should be replaced with the configured replacement. Be sure to change the configurations around to see if it behaves in a way you expect.

You should also add a few new patterns by clicking on "Redact Values > Patterns". Add a new regular expression pattern, set it to a new redaction, and see if it works.

**Comment by katknow** [comment]
For the most part, it seems I'm able to do everything in a variety of combinations. Tried omitting research and author; tried URL, email, and IP addresses; tried on Items, Item Sets, and Media; multiple at once for difference users; was able to query successfully; could add/delete/edit redactions and see reflected changes. The one issue I'm coming into is adding a pattern. I tried to add Date redact, and now when I view the date field I see this: 

`Warning: preg_replace(): Unknown modifier '.' in /var/www/html/katknow/OmekaSTesting/modules/RedactValues/Module.php on line 148`

There is a very good chance this is user error as this is my first time using https://www.regular-expressions.info/. I copied the following date info from the first example here: https://www.regular-expressions.info/dates.html 

`^(19|20)\d\d[- /.](0[1-9]|1[012])[- /.](0[1-9]|[12][0-9]|3[01])$`

**Comment by jimsafley** [comment]
I'm really glad you found that bug. I've made some changes that should fix it. After pulling, you'll need to uninstall and reinstall the module. Note that you now need to enclose your pattern with [delimiters](https://www.php.net/manual/en/regexp.reference.delimiters.php). Something like this:

```
<^(19|20)\d\d[- /.](0[1-9]|1[012])[- /.](0[1-9]|[12][0-9]|3[01])$>
```

**Comment by katknow** [comment]
That fixed it--I am now able to add my own patterns and it operates just as the others do. (Also, thanks for the info on delimiters!)
