### ISSUE TITLE
Documentation: Redact Values module

### ISSUE THREAD

**Issue by jimsafley** [omeka-s-modules/RedactValues#2]
This module needs user documentation. It's pretty straightforward given that the redaction and pattern forms are self-documenting.

One thing to note is that the module does _not_ apply redactions for users who have permission to update the resource. That means that values will never be redacted for **global admins**, **supervisors**, and **editors**. Normally, values will be redacted for **authors** except for resources that they own. Normally, all values will be redacted for **researchers**. You can configure each redaction to allow **authors** and/or **researchers** to view otherwise redacted values. Users who are not logged in will never be able to view redacted values.

**Comment by sharonmleon** [comment]
@katknow Would you like to take a swipe at writing the documentation for this module since you've done the most work with it? You could just make a branch for it in the [omeka-s-enduser repo](https://github.com/omeka/omeka-s-enduser)

**Comment by katknow** [comment]
@sharonmleon can do, might just be later in the week if that's okay

**Comment by sharonmleon** [comment]
@katknow That would be great. Let me know if you have any questions along the way.

**Comment by katknow** [comment]
Still need to probably break up the text a bit and add alt-text to images but here's a first draft:
https://github.com/omeka/omeka-s-enduser/blob/1982eaade95cd7bef132904f39c3f719d59a797d/docs/modules/redactvalues.md

**Comment by jimsafley** [comment]
I think it's fantastic. Well done!
